# Generated by Django 5.1.2 on 2026-10-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_unique_recommended_stopper_per_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.TextField(blank=True, help_text='Identificadores de alérgenos separados por coma', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='celiac_info',
            field=models.JSONField(blank=True, help_text='Declaraciones SIN TACC; null = desactivado', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='featured_ingredients',
            field=models.TextField(blank=True, help_text='Ingredientes destacados separados por coma (máx. 8)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='presentation',
            field=models.JSONField(blank=True, help_text='Presentación: cantidad, dimensiones y rendimiento (versionado)', null=True),
        ),
    ]
